import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { DeferredToaster } from "~/components/ui/deferred-toaster";

export const metadata: Metadata = {
  title: "Roundest Cache",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/poke-favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body
        className={`flex min-h-screen flex-col justify-between text-gray-600 antialiased`}
      >
        <main className="flex-1">{children}</main>

        <DeferredToaster richColors />
      </body>
    </html>
  );
}
